#!/usr/bin/env bash
# Install OpenClaw (the D21 "brain") into a project-local npm prefix using the
# pixi-provided Node/npm. Never `npm i -g`: nothing is written outside the repo
# except npm's own download cache, and `node/` is gitignored so the ~300-package
# dependency tree never enters git.
#
# Run it through pixi so Node 24 is on PATH:  pixi run install-openclaw
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
prefix="$repo_root/node"

mkdir -p "$prefix"

# The prefix manifest is generated, not tracked. Its `allowScripts` field names
# the dependencies permitted to run install-time lifecycle scripts -- openclaw's
# own postinstall unpacks its bundled plugins, and the other three build or
# no-op. npm 11 still runs unapproved scripts and merely warns, but a future npm
# will block them, so declaring the list here keeps this install working across
# that change. (npm rejects the equivalent `--allow-scripts` CLI flag for
# project-scoped installs: it must live in package.json or .npmrc.)
cat > "$prefix/package.json" <<'JSON'
{
  "name": "sisyphus-openclaw-prefix",
  "private": true,
  "description": "Generated by scripts/install_openclaw.sh -- do not edit or commit.",
  "allowScripts": {
    "openclaw": true,
    "@google/genai": true,
    "protobufjs": true,
    "tree-sitter-bash": true
  }
}
JSON

npm install --prefix "$prefix" --no-fund --no-audit openclaw

"$prefix/node_modules/.bin/openclaw" --version
